### ISSUE TITLE
Tutorial 02 (Swap chains) use PresentQueue where GraphicsQueue should be used

### ISSUE THREAD

**Issue by kosumosu** [GameTechDev/IntroductionToVulkan#16]
Currently in Tutorial02.cpp:798 there's a call:
`if( vkQueueSubmit( Vulkan.PresentQueue, 1, &submit_info, VK_NULL_HANDLE ) != VK_SUCCESS )`

If I get it right, Vulkan.PresentQueue is incorrectly used instead of Vulkan.GraphicsQueue.
Otherwise Vulkan.GraphicsQueue is never used.
This works for 99% people because both handles point to the same queue in most cases.

**Comment by Ekzuzy** [comment]
You are right that graphics queue is not used at all, but this done on purpose. I didn't want to introduce too many topics at once, so in this tutorial I present how to record very simple command buffers - they only setup an image barrier, clear an image and setup another barrier to see if anything is displayed at all. Clearing can be performed both on compute and graphics queue, that's why I used a present queue for this. This should work practically everywhere and I didn't need to bother readers with an image ownership transfer.

**Comment by kosumosu** [comment]
Ok, I should have read the article to the end first :)
